<h1>4.1 데이터 종류</h1>
<img src="../ch4/img/data_type.png" alt="data_type">

<h3>4.1.1 수치형 데이터</h3>

<b>수치형 데이터(numerical data)</b>는 사칙 연산이 가능한 데이터. data type으로는 int, float, bool 등이 있다. (bool은 0과 1로 표현되기에 사칙 연산이 가능.)


<li>연속형 데이터(continuous data): 데이터가 연속적으로 이어진다. 예를 들어, 키, 몸무게, 온도 등이 있다.</li>
<br>
<li>이산형 데이터(discrete data): 데이터가 이산적으로 이어진다. 예를 들어, 사람의 수, 소의 수, 차의 수 등이 있다.</li>
<br>

*연속형은 실수형, 이산형은 정수형 데이터*

<h3>4.1.2 범주형 데이터</h3>

<b>범주형 데이터(categorical data)</b>는 범주를 나눌 수 있는 데이터이며 사칙 연산이 불가능한 데이터. data type으로는 object, category 등이 있다.(여기서 object와 category는 pandas라이브러리에서 사용됨. object는 string type과 동일하지만, category는 고유한 값을 가진 데이터로 효율 적으로 메모리 관리 할 수 있께 해줌)


<li>순서형 데이터(ordinal data)</b>순위를 매길 수 있는 데이터. 예를 들어, 학점(A, B, C, D) 등이 있다.</li>
<br>
<li>명목형 데이터(nominal data)</b>순위가 따로 존재하지 않는 데이터. 예를 들어, 성별(남, 여) 등이 있다. 또한 우편번호 역시 숫자로 되어있지만 사칙연산과 관련 없고 순위가 존재하지 않기 때문에 명목형으로 분류된다.</li>
<br>

<h2>4.2 탐색적 데이터 분석과 그래프</h2>

In [7]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [11]:
titanic.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [12]:
titanic.tail(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

<h2>4.3 수치형 데이터 시각화</h2>

<li>histplot(): 히스토그램</li>
<br/>
<li>kdeplot(): 커널 밀도 추정 그래프</li>
<br/>
<li>distplot(): 분포도(히스토그램과 kdeplot을 합친 그래프)</li>
<br/>
<li>rugplot(): 데이터의 밀도를 나타내는 그래프</li>